# Generated by Django 5.0.1 on 2024-01-29 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crow', '0002_project_image_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, default='media/project/no_image.jpg', null=True, upload_to=''),
        ),
    ]
