# Generated by Django 5.0.1 on 2025-01-14 12:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crow', '0002_auto_20241203_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='closure_type',
            field=models.CharField(default='BY_AMOUNT', help_text='Тип закрытия проекта. BY_AMOUNT - закрытие сбора по определенной сумме, BY_TIME - закрытие сбора по истечении времени', max_length=10),
        ),
        migrations.AlterField(
            model_name='project',
            name='status_code',
            field=models.ForeignKey(help_text='Статус код проекта. 0 - не поступил в работу, 1 - в работе, 2 - сбор приостановлен, 3 - в архиве', null=True, on_delete=django.db.models.deletion.CASCADE, to='crow.projectstatuscode'),
        ),
        migrations.AlterField(
            model_name='project',
            name='transfer_allowed',
            field=models.BooleanField(default=False, help_text='Поле для разрешения снятии средств с проекта'),
        ),
        migrations.AlterField(
            model_name='projectstatuscode',
            name='code',
            field=models.IntegerField(help_text='Код статуса'),
        ),
        migrations.AlterField(
            model_name='projectstatuscode',
            name='name',
            field=models.CharField(help_text='Название статуса', max_length=255),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(help_text='Название умений', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='about',
            field=models.CharField(blank=True, help_text='О пользователе', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.DateField(blank=True, help_text='Дата рождения пользователя', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='category',
            field=models.ManyToManyField(help_text='Интересные категории проектов для пользователя', to='crow.category'),
        ),
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, help_text='Город проживания', max_length=170, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='company',
            field=models.CharField(blank=True, help_text='Компания в которой работает пользователь', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='confirmed',
            field=models.BooleanField(default=False, help_text='Подтвержден дли пользователь в системе'),
        ),
        migrations.AlterField(
            model_name='user',
            name='document',
            field=models.CharField(blank=True, help_text='Документ пользователя', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email_verified',
            field=models.BooleanField(default=False, help_text='Подтверждена ли почта пользователя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='money',
            field=models.FloatField(blank=True, default=0, help_text='Актнуальный счет пользователя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='passport',
            field=models.CharField(blank=True, help_text='Паспортные данные пользователя', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.CharField(blank=True, help_text='Пол пользователя. М/Ж', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='skill',
            field=models.ManyToManyField(help_text='Уменя пользователя', to='crow.skill'),
        ),
        migrations.AlterField(
            model_name='user',
            name='total_money_sent',
            field=models.FloatField(blank=True, default=0, help_text='Сколько всего задонатил пользователь'),
        ),
        migrations.CreateModel(
            name='CashingOutProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cashing_out_project', to='crow.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cashing_out_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
