# Generated by Django 5.0.1 on 2024-10-29 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crow', '0002_auto_20241029_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='transfer_allowed',
            field=models.BooleanField(default=False),
        ),
    ]
