# Generated by Django 5.0.1 on 2024-10-31 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crow', '0003_project_transfer_allowed'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='closure_type',
            field=models.CharField(default='M', max_length=1),
            preserve_default=False,
        ),
    ]
