# Generated by Django 5.0.1 on 2025-01-14 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crow', '0003_alter_project_closure_type_alter_project_status_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashingoutproject',
            name='money',
            field=models.BigIntegerField(default=0),
        ),
    ]
