# Generated by Django 5.0.1 on 2024-01-29 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crow', '0003_alter_project_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, default='projects/no_image.jpg', null=True, upload_to='project/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='users/user.png', null=True, upload_to='users/'),
        ),
    ]
