# Generated by Django 5.0.1 on 2025-02-19 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crow', '0003_post_imagetopost'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='datetime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='posts/no_image.jpg', upload_to='posts/'),
        ),
    ]
