# Generated by Django 5.0.1 on 2024-01-29 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crow', '0004_alter_project_image_alter_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(default='projects/no_image.jpg', upload_to='project/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='users/user.png', upload_to='users/'),
        ),
    ]
