# Generated by Django 5.0.1 on 2025-01-14 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crow', '0004_cashingoutproject_money'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashingoutproject',
            name='actual_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='cashingoutproject',
            name='money',
            field=models.FloatField(default=0),
        ),
    ]
