# Generated by Django 5.0.1 on 2024-10-31 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crow', '0004_project_closure_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='closure_type',
            field=models.CharField(default='BY_AMOUNT', max_length=1),
        ),
    ]
