# Generated by Django 5.0.1 on 2025-01-15 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crow', '0005_cashingoutproject_actual_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='project',
            name='views',
        ),
        migrations.AddField(
            model_name='project',
            name='views',
            field=models.ManyToManyField(related_name='project_views', to='crow.ip'),
        ),
    ]
