# Generated by Django 5.0.1 on 2024-10-31 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crow', '0005_alter_project_closure_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='closure_type',
            field=models.CharField(default='BY_AMOUNT', max_length=10),
        ),
    ]
