# Generated by Django 5.0.1 on 2024-02-01 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crow', '0005_alter_project_image_alter_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='small_description',
            field=models.CharField(default=456, max_length=150),
            preserve_default=False,
        ),
    ]
