# Generated by Django 5.0.1 on 2025-03-23 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crow', '0005_refund'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilechangerequest',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
    ]
