# Generated by Django 5.0.1 on 2025-01-15 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crow', '0006_ip_remove_project_views_project_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ip',
            name='ip',
            field=models.CharField(max_length=100),
        ),
    ]
