# Generated by Django 5.0.1 on 2024-11-01 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crow', '0007_projectclosurerequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectclosurerequest',
            name='answer_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='projectclosurerequest',
            name='allowed',
            field=models.BooleanField(null=True),
        ),
    ]
