# Generated by Django 5.0.1 on 2024-02-01 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crow', '0007_alter_project_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='about',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='О себе'),
        ),
        migrations.AlterField(
            model_name='user',
            name='money',
            field=models.FloatField(blank=True, default=0, verbose_name='Баланс'),
        ),
    ]
