# Generated by Django 5.0.1 on 2024-11-01 14:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crow', '0008_projectclosurerequest_answer_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectclosurerequest',
            name='admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='admin_project_closure', to=settings.AUTH_USER_MODEL),
        ),
    ]
