# Generated by Django 5.0.1 on 2024-02-01 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crow', '0008_user_about_alter_user_money'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
