# Generated by Django 5.0.1 on 2025-01-29 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crow', '0008_alter_project_options_accountreplenishment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountreplenishment',
            name='idempotence_key',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
    ]
