# Generated by Django 5.0.1 on 2024-11-26 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crow', '0009_alter_projectclosurerequest_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilechangerequest',
            name='create_date',
            field=models.DateField(null=True),
        ),
    ]
