# Generated by Django 5.0.1 on 2025-01-30 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crow', '0009_alter_accountreplenishment_idempotence_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountreplenishment',
            name='change_status_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accountreplenishment',
            name='create_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
