# Generated by Django 5.0.1 on 2024-02-12 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crow', '0010_project_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='total_money_sent',
            field=models.FloatField(blank=True, default=0, verbose_name='Сумма поддержек'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=27, unique=True),
        ),
    ]
