# Generated by Django 5.0.1 on 2024-11-28 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crow', '0010_alter_profilechangerequest_create_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionRules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_percentage', models.IntegerField()),
                ('max_percentage', models.IntegerField()),
                ('commission_rate', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='projectchangerequest',
            name='create_date',
            field=models.DateField(null=True),
        ),
    ]
