# Generated by Django 5.0.1 on 2025-01-30 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crow', '0010_accountreplenishment_change_status_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountreplenishment',
            name='payment_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
