# Generated by Django 5.0.1 on 2024-02-13 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crow', '0011_user_total_money_sent_alter_project_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AddField(
            model_name='user',
            name='category',
            field=models.ManyToManyField(to='crow.category'),
        ),
    ]
