# Generated by Django 5.0.1 on 2025-02-03 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crow', '0011_accountreplenishment_payment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashingoutproject',
            name='change_status_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cashingoutproject',
            name='create_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cashingoutproject',
            name='idempotence_key',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='cashingoutproject',
            name='payout_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cashingoutproject',
            name='status',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
