# Generated by Django 5.0.1 on 2024-11-28 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crow', '0011_commissionrules_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commissionrules',
            name='commission_rate',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='commissionrules',
            name='max_percentage',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='commissionrules',
            name='min_percentage',
            field=models.FloatField(),
        ),
    ]
