# Generated by Django 5.0.1 on 2024-02-15 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crow', '0012_user_birthday_user_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, max_length=170, null=True, verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='user',
            name='skill',
            field=models.ManyToManyField(to='crow.skill'),
        ),
    ]
