# Generated by Django 5.0.1 on 2025-02-05 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crow', '0012_cashingoutproject_change_status_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cashingoutproject',
            name='change_status_date',
        ),
        migrations.RemoveField(
            model_name='cashingoutproject',
            name='idempotence_key',
        ),
        migrations.RemoveField(
            model_name='cashingoutproject',
            name='payout_id',
        ),
        migrations.RemoveField(
            model_name='cashingoutproject',
            name='status',
        ),
    ]
