# Generated by Django 5.0.1 on 2024-11-28 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crow', '0013_alter_commissionrules_commission_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commissionrules',
            name='commission_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commissionrules',
            name='max_percentage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commissionrules',
            name='min_percentage',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
