# Generated by Django 5.0.1 on 2024-04-03 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crow', '0013_skill_user_city_user_skill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(default='project/no_image.jpg', upload_to='project/'),
        ),
    ]
