# Generated by Django 5.0.1 on 2024-07-10 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crow', '0014_alter_project_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=27, unique=True)),
                ('small_description', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=1000)),
                ('need_money', models.FloatField()),
                ('end_date', models.DateField()),
                ('image', models.ImageField(default='project/no_image.jpg', upload_to='project/')),
                ('confirmed', models.BooleanField(default=None, null=True)),
                ('category', models.ManyToManyField(to='crow.category')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='change_requests', to='crow.project')),
            ],
        ),
    ]
