# Generated by Django 5.0.1 on 2025-02-05 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crow', '0014_payout'),
    ]

    operations = [
        migrations.AddField(
            model_name='payout',
            name='payout_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
