# Generated by Django 5.0.1 on 2024-07-10 11:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crow', '0015_projectchangerequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectchangerequest',
            name='admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='change_requests_admin', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectchangerequest',
            name='ask_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='projectchangerequest',
            name='create_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='projectchangerequest',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='change_requests_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projectchangerequest',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='change_requests_project', to='crow.project'),
        ),
    ]
