# Generated by Django 5.0.1 on 2025-02-05 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crow', '0015_payout_payout_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payout',
            name='payout_id',
            field=models.CharField(blank=True, null=True),
        ),
    ]
