# Generated by Django 5.0.1 on 2024-07-10 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crow', '0016_projectchangerequest_admin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectchangerequest',
            name='description_for_change',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
    ]
