# Generated by Django 5.0.1 on 2025-02-09 15:19

from django.db import migrations

def init_data(apps, schema_editor):


    CommissionRules = apps.get_model("crow", "CommissionRules")
    CommissionRules.objects.create(min_percentage=50, max_percentage=90, commission_rate=15)
    CommissionRules.objects.create(min_percentage=90, max_percentage=100, commission_rate=10)




class Migration(migrations.Migration):

    dependencies = [
        ('crow', '0016_alter_payout_payout_id'),
    ]

    operations = [
        migrations.RunPython(init_data),
    ]
