# Generated by Django 5.0.1 on 2024-07-10 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crow', '0017_projectchangerequest_description_for_change'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectchangerequest',
            old_name='ask_date',
            new_name='answer_date',
        ),
    ]
