# Generated by Django 5.0.1 on 2024-07-10 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crow', '0018_rename_ask_date_projectchangerequest_answer_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectchangerequest',
            name='name',
            field=models.CharField(max_length=27),
        ),
    ]
