# Generated by Django 5.0.1 on 2024-07-10 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crow', '0019_alter_projectchangerequest_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectchangerequest',
            name='answer_description',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
    ]
