# Generated by Django 5.0.1 on 2024-07-10 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crow', '0020_projectchangerequest_answer_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectchangerequest',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='projectchangerequest',
            name='need_money',
            field=models.FloatField(null=True),
        ),
    ]
