# Generated by Django 5.0.1 on 2024-07-24 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crow', '0021_alter_projectchangerequest_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectchangerequest',
            name='answer_date',
            field=models.DateTimeField(null=True),
        ),
    ]
