# Generated by Django 5.0.1 on 2024-07-24 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crow', '0022_alter_projectchangerequest_answer_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.ManyToManyField(related_name='project_category', to='crow.category'),
        ),
    ]
