# Generated by Django 5.0.1 on 2024-07-30 18:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crow', '0025_verificationtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationtoken',
            name='token',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
