# Generated by Django 5.0.1 on 2024-08-04 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crow', '0027_resetpasswordtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resetpasswordtoken',
            name='token',
            field=models.CharField(),
        ),
    ]
