# Generated by Django 5.0.1 on 2024-08-13 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('crow', '0029_alter_user_about_alter_user_birthday_alter_user_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilechangerequest',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='change_requests_group', to='auth.group'),
            preserve_default=False,
        ),
    ]
