# Generated by Django 5.0.1 on 2024-08-13 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crow', '0031_remove_profilechangerequest_admin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answerprofilechangerequest',
            name='answer_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='profilechangerequest',
            name='create_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
