# Generated by Django 5.0.1 on 2024-08-13 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crow', '0032_answerprofilechangerequest_answer_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilechangerequest',
            name='about',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='profilechangerequest',
            name='city',
            field=models.CharField(max_length=170, null=True),
        ),
        migrations.AlterField(
            model_name='profilechangerequest',
            name='company',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='profilechangerequest',
            name='description_for_change',
            field=models.CharField(max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='profilechangerequest',
            name='document',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profilechangerequest',
            name='passport',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='profilechangerequest',
            name='sex',
            field=models.CharField(max_length=1, null=True),
        ),
    ]
