# Generated by Django 5.0.1 on 2024-08-16 12:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crow', '0033_alter_profilechangerequest_about_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilechangerequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='change_profile_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
