# Generated by Django 5.0.1 on 2024-08-16 13:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crow', '0034_alter_profilechangerequest_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilechangerequest',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='change_requests_profile', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
