# Generated by Django 5.0.1 on 2024-08-20 09:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crow', '0035_profilechangerequest_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilechangerequest',
            name='admin',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='change_profile_admin', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profilechangerequest',
            name='answer_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='profilechangerequest',
            name='answer_description',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='profilechangerequest',
            name='confirmed',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.DeleteModel(
            name='AnswerProfileChangeRequest',
        ),
    ]
