# Generated by Django 5.0.1 on 2024-08-20 09:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crow', '0036_profilechangerequest_admin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilechangerequest',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='profilechangerequest',
            name='answer_date',
        ),
        migrations.RemoveField(
            model_name='profilechangerequest',
            name='answer_description',
        ),
        migrations.RemoveField(
            model_name='profilechangerequest',
            name='confirmed',
        ),
        migrations.CreateModel(
            name='AnswerProfileChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_description', models.CharField(blank=True, max_length=2048, null=True)),
                ('confirmed', models.BooleanField(default=None, null=True)),
                ('answer_date', models.DateTimeField(null=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='change_profile_admin', to=settings.AUTH_USER_MODEL)),
                ('change_profile_request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='change_profile_request', to='crow.profilechangerequest')),
            ],
        ),
    ]
