# Generated by Django 5.0.1 on 2024-08-21 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crow', '0037_remove_profilechangerequest_admin_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answerprofilechangerequest',
            old_name='change_profile_request',
            new_name='profile',
        ),
    ]
