# Generated by Django 5.0.1 on 2024-08-21 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crow', '0038_rename_change_profile_request_answerprofilechangerequest_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answerprofilechangerequest',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='answer_request', to='crow.profilechangerequest'),
        ),
    ]
