# Generated by Django 5.0.1 on 2024-08-23 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('crow', '0039_alter_answerprofilechangerequest_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilechangerequest',
            name='first_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='profilechangerequest',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='change_requests_group', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='profilechangerequest',
            name='last_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='profilechangerequest',
            name='username',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
