# Generated by Django 5.0.1 on 2024-08-27 13:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crow', '0040_alter_profilechangerequest_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectchangerequest',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='projectchangerequest',
            name='answer_date',
        ),
        migrations.RemoveField(
            model_name='projectchangerequest',
            name='answer_description',
        ),
        migrations.RemoveField(
            model_name='projectchangerequest',
            name='confirmed',
        ),
        migrations.CreateModel(
            name='AnswerProjectChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_description', models.CharField(blank=True, max_length=2048, null=True)),
                ('confirmed', models.BooleanField(default=None, null=True)),
                ('answer_date', models.DateTimeField(null=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='admin_change_requests_project', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='answer_change_requests_project', to='crow.projectchangerequest')),
            ],
        ),
    ]
