# Generated by Django 5.0.1 on 2024-08-27 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crow', '0041_remove_projectchangerequest_admin_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answerprojectchangerequest',
            old_name='project',
            new_name='change_request',
        ),
    ]
