# Generated by Django 5.0.1 on 2024-09-11 14:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crow', '0043_projectconfirmanswer'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileConfirmAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=1000, null=True)),
                ('confirmed', models.BooleanField()),
                ('answer_time', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confirm_profile_answer', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confirm_profile_admin', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
