# Generated by Django 5.0.1 on 2024-09-23 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crow', '0046_alter_projectimages_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectimages',
            name='image',
            field=models.CharField(),
        ),
    ]
