# Generated by Django 5.0.1 on 2024-09-23 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crow', '0047_alter_projectimages_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectimages',
            name='image',
            field=models.ImageField(upload_to='project/'),
        ),
    ]
