# Generated by Django 5.0.1 on 2024-09-23 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crow', '0048_alter_projectimages_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectimages',
            name='image',
            field=models.CharField(),
        ),
    ]
