# Generated by Django 5.0.1 on 2024-09-26 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crow', '0050_alter_projectimages_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewImageToProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='project/')),
                ('project_change_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='add_image', to='crow.projectchangerequest')),
            ],
        ),
    ]
