# Generated by Django 5.0.1 on 2024-10-29 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crow', '0051_newimagetoproject'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectStatusCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='status_code',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='crow.projectstatuscode'),
            preserve_default=False,
        ),
    ]
