# Generated by Django 5.0.1 on 2024-10-29 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crow', '0052_projectstatuscode_project_status_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='status_code',
        ),
        migrations.DeleteModel(
            name='ProjectStatusCode',
        ),
    ]
